### ISSUE TITLE
why not use post method in retrieveAndProcessToken function

### ISSUE THREAD

**Issue by wanyoung1231** [spira/angular-jwt-auth#27]
I have seen lots of plugins that use `post` method, my server side use flask-jwt that just support `post` method

**Comment by zakhenry** [comment]
This service is intended to be used with a REST compliant API. The HTTP `POST` method is intended to be used to represent the creation of resources. One of the key features of json web token is that there are no resources persisted on the server (in cache, memory, database or otherwise), so it is more appropriate that the method be `GET`.

**Comment by zakhenry** [comment]
@young-py I'm open to pull requests that make the method configurable, but I am happy with the choice of `GET` as the appropriate method.

Relevant code block for reference https://github.com/spira/angular-jwt-auth/blob/master/src/ngJwtAuthService.ts#L155

**Comment by wanyoung1231** [comment]
I got it, Thanks! By the way, i have questions about `exchangeToken` function, what's it be used to for?

**Comment by zakhenry** [comment]
The purpose of the `exchangeToken` method is to authenticate with a token rather than with username/password. This is a different method as it uses a different authentication header. 

The `exchangeToken` method uses `Authorization: Bearer <token>` header whereas credential authentication uses `Authorization: Basic <basiccredentials>` header.

You might want to use token authentication for things like password reset emails or other single use tokens. It is the exchange of a non-jwt token for a JWT.

**Comment by wanyoung1231** [comment]
Thank you very much, I understand!

**Comment by zakhenry** [comment]
@young-py sorry the documentation is quite lacking at the moment, your best bet for support is the typescript source files as they are reasonable well commented.

I intend to add a wiki soon now that the codebase is stable and being used in https://github.com/spira/spira
